name: based_qr
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Cierra-Runis/based_widget/packages/based_qr

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.1
  flutter_shaders: ^0.1.2
  pretty_qr_code: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
