name: based_splash_page
description: A Based Splash Page
version: 1.0.1+1
homepage: https://github.com/Cierra-Runis/based_flutter/tree/master/packages/based_splash_view

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
