name: based_split_view
description: A Based Split View Widget, Which Helps You Create A Split View In Large Screen Device like Telegram, QQ or Discord
version: 1.0.0
homepage: https://github.com/Cierra-Runis/based_split_view

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
