name: based_list
description: A Based Sequence Of Widgets About List
version: 1.1.3+1
homepage: https://github.com/Cierra-Runis/based_flutter/tree/master/packages/based_list

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
