name: based_avatar
description: A Based Widget For Building More Useful Avatar
version: 1.0.4+1
homepage: https://github.com/Cierra-Runis/based_flutter/tree/master/packages/based_avatar

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
